#!/bin/bash
# Quick Testing Commands for Real-Time Chat

echo "🚀 REAL-TIME CHAT - QUICK TEST COMMANDS"
echo "========================================"
echo ""

# Test 1: Run Flutter with chat logs visible
echo "📱 Test 1: Watch Chat Messages & Connection"
echo "Command: flutter run --verbose 2>&1 | grep -E '(CHAT|MESSAGE|CONNECTED|CONVERSATION|SEND|RECEIVE)'"
echo ""

# Test 2: Monitor all errors
echo "🔴 Test 2: Monitor Errors Only"
echo "Command: flutter run --verbose 2>&1 | grep -E '(ERROR|❌|Exception)'"
echo ""

# Test 3: Monitor WebSocket connection
echo "🔌 Test 3: Monitor WebSocket Connection"
echo "Command: flutter run --verbose 2>&1 | grep -E '(WebSocket|CONNECTED|DISCONNECTED|socket)'"
echo ""

# Test 4: Monitor message flow
echo "💬 Test 4: Monitor Message Flow (Send/Receive)"
echo "Command: flutter run --verbose 2>&1 | grep -E '(Sending|Received|optimistic|Reconciling)'"
echo ""

echo "========================================"
echo "TESTING SCENARIOS:"
echo "========================================"
echo ""

echo "✅ Scenario 1: Message Sending & Status"
echo "  1. Open app on Device A & B"
echo "  2. Device A: Type message and send"
echo "  3. Expected: Message appears INSTANTLY with ⏱ status"
echo "  4. Expected after 1-2 sec: Status changes to ✓"
echo "  5. Expected on Device B: Message appears automatically"
echo ""

echo "✅ Scenario 2: Read Receipts"
echo "  1. Device A: Send message"
echo "  2. Device B: View conversation"
echo "  3. Expected: Device A sees message status → ✓✓ (read)"
echo "  4. Check logs for: '📖 Read receipt received'"
echo ""

echo "✅ Scenario 3: Typing Indicator"
echo "  1. Device A: Start typing in message field"
echo "  2. Expected on Device B: '${recipient.name} is typing...'"
echo "  3. Device A: Stop typing"
echo "  4. Expected on Device B: Indicator disappears after 3 seconds"
echo ""

echo "✅ Scenario 4: Connection Status"
echo "  1. Look at app - should show '🟢 Connected' in header"
echo "  2. Enable Airplane Mode on Device"
echo "  3. Expected: Status changes to '🔴 Disconnected'"
echo "  4. Disable Airplane Mode"
echo "  5. Expected: Reconnects automatically, shows '🟢 Connected'"
echo ""

echo "========================================"
echo "KEY LOGS TO WATCH:"
echo "========================================"
echo ""
echo "🟢 Connection Success:"
echo "   '🟢 WebSocket CONNECTED'"
echo "   '👂 Subscribing to /user/{id}/queue/messages'"
echo ""

echo "💬 Message Sending:"
echo "   '💬 Sending message: clientId={id}, to={recipientId}'"
echo "   '✨ Optimistic message emitted to UI'"
echo "   '📤 Sending via /app/chat.send'"
echo ""

echo "📥 Message Receiving:"
echo "   '📥 Message received on /queue/messages'"
echo "   '♻️ Reconciling optimistic message {clientId} → server ID {id}'"
echo "   '✅ Message emitted to listeners'"
echo ""

echo "📖 Read Receipts:"
echo "   '📖 Read receipt: message {id} read by {userId}'"
echo "   '📖 Bulk read receipts: {count} messages'"
echo ""

echo "⌨️ Typing Indicators:"
echo "   '⌨️ Sending typing indicator: isTyping=true to {recipientId}'"
echo "   '⌨️ Typing indicator received'"
echo "   '⌨️ {userId} isTyping=true'"
echo ""

echo "❌ Errors:"
echo "   '❌ WebSocket ERROR: {error}'"
echo "   '❌ WebSocket not connected, cannot send message'"
echo "   '❌ Error parsing message: {error}'"
echo ""

echo "========================================"
echo "EXPECTED LOG SEQUENCE (for 1 message):"
echo "========================================"
echo ""
echo "1. [USER] Types message, clicks send"
echo "   └─ '⌨️ Sending typing indicator: isTyping=false'"
echo ""
echo "2. [SEND] App sends optimistically"
echo "   ├─ '💬 Sending message: clientId=1234...'"
echo "   ├─ '✨ Optimistic message emitted to UI'"
echo "   └─ '📤 Sending via /app/chat.send: {...}'"
echo ""
echo "3. [SERVER] Backend receives and broadcasts"
echo "   └─ '✅ WebSocket send() called successfully'"
echo ""
echo "4. [RECEIVE] Client receives confirmation"
echo "   ├─ '📥 Message received on /queue/messages'"
echo "   ├─ '📨 Decoded message: id=42 from={senderId}'"
echo "   ├─ '♻️ Reconciling optimistic message 1234 → server ID 42'"
echo "   └─ '✅ Message emitted to listeners'"
echo ""
echo "5. [RECIPIENT] Recipient receives message"
echo "   ├─ '📥 Message received on /queue/messages'"
echo "   ├─ '📨 Decoded message: id=42 from=1'"
echo "   └─ '✅ Message emitted to listeners'"
echo ""
echo "6. [READ] Recipient reads message"
echo "   ├─ '📖 Marking message 42 as read'"
echo "   └─ '✅ Mark as read sent for message 42'"
echo ""
echo "7. [SENDER] Sender sees read receipt"
echo "   ├─ '📥 Notification received on /queue/notifications'"
echo "   ├─ '📖 Read receipt: message [42] read by 2'"
echo "   └─ '✅ Message status updated to READ'"
echo ""

echo "========================================"
echo "QUICK COMMANDS TO RUN:"
echo "========================================"
echo ""
echo "# Full app with all logs"
echo "flutter run"
echo ""
echo "# Filter to chat messages only"
echo "flutter logs | grep -i 'chat\\|message\\|typing\\|read'"
echo ""
echo "# Monitor connection only"
echo "flutter logs | grep -i 'connected\\|websocket'"
echo ""
echo "# Show errors only"
echo "flutter logs | grep -i 'error\\|exception\\|❌'"
echo ""
echo "# Complete flow (most useful)"
echo "flutter logs | grep -E '(💬|📥|📤|♻️|✅|📖|⌨️|🟢|🔴)'"
echo ""

echo "========================================"
echo "Pro Tip: Use regex filtering in your terminal!"
echo "flutter logs | grep -E 'PATTERN' shows only matching lines"
echo "========================================"
