// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn-f2j_CjW9Voq8gY_bhMbnjwTKN31JF8',
    appId: '1:900647534857:web:8ebb37324dce410d4293d8',
    messagingSenderId: '900647534857',
    projectId: 'social-chat-app-e2115',
    authDomain: 'social-chat-app-e2115.firebaseapp.com',
    storageBucket: 'social-chat-app-e2115.firebasestorage.app',
    measurementId: 'G-6P944ZSXY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGkKYtExMt4PIhzqBvOdTAz18EaQlhPLs',
    appId: '1:900647534857:android:7c00f8e0254138544293d8',
    messagingSenderId: '900647534857',
    projectId: 'social-chat-app-e2115',
    storageBucket: 'social-chat-app-e2115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6qPpUpyLCkkIAfXN9UaW8xZ49H63QEgo',
    appId: '1:900647534857:ios:5f6904eaba4e00394293d8',
    messagingSenderId: '900647534857',
    projectId: 'social-chat-app-e2115',
    storageBucket: 'social-chat-app-e2115.firebasestorage.app',
    iosBundleId: 'com.example.socialChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6qPpUpyLCkkIAfXN9UaW8xZ49H63QEgo',
    appId: '1:900647534857:ios:5f6904eaba4e00394293d8',
    messagingSenderId: '900647534857',
    projectId: 'social-chat-app-e2115',
    storageBucket: 'social-chat-app-e2115.firebasestorage.app',
    iosBundleId: 'com.example.socialChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn-f2j_CjW9Voq8gY_bhMbnjwTKN31JF8',
    appId: '1:900647534857:web:8fc34eb9524fd9624293d8',
    messagingSenderId: '900647534857',
    projectId: 'social-chat-app-e2115',
    authDomain: 'social-chat-app-e2115.firebaseapp.com',
    storageBucket: 'social-chat-app-e2115.firebasestorage.app',
    measurementId: 'G-54D617LQZ5',
  );
}
